---
# tasks file for sdelete

- name: Copy sdelete64 tool
  win_copy:
    src: '{{ scripts_location }}/SDelete.zip'
    dest: '{{ src }}\SDelete.zip'

- name: 7zip install and extract in Windows Server 2008 R2 cases
  import_tasks: 7zip_install.yml
  when: "ansible_facts['os_family'] == 'Windows' and ansible_facts['distribution_version'] == '6.1.7601.65536'"

- name: Unzip SDelete.zip
  win_unzip:
     src: '{{ src }}\SDelete.zip'
     dest: '{{ src }}\SDelete'
  when: "ansible_facts['os_family'] == 'Windows' and ansible_facts['distribution_version'] != '6.1.7601.65536'"

- name: Run SDelete64.exe on C drive
  # win_command: 'C:\users\rozz01cs\Downloads\SDelete\sdelete64.exe -accepteula -z {{ drive }} >> C:\users\rozz01cs\Downloads\SDelete\sdelete64.txt'
  win_command: '{{ src }}\SDelete\sdelete64.exe -accepteula -z {{ drive }}'
  register: sdelete
- debug: var=sdelete.stdout_lines  

- name: Remove SDelete files and folders
  win_file:
    path: '{{ src }}\{{ item }}'
    state: absent
  with_items:
    - SDelete.zip
    - SDelete      




