---
#tasks file for win2012_upgrade_2016
- name: Extend system C drive
  import_tasks: extendCdrive.yml
- name: Copy and mount Wndows Server 2016 ISO
  import_tasks: pre_upgrade.yml
- name: Run Windows Server 2016 OS upgrade
  import_tasks: upgrade.yml
- name: Wait for system to become reachable over WinRM after OS upgrade
  wait_for_connection:
     delay: 600
     timeout: 9600
#- name: Wait 3600 seconds for RDP port 3389 to become open on the host, don't start checking for 10 seconds
#  win_wait_for:
#    port: 3389
#    timeout: 3600
#    delay: 60
- name: Cleanup Wndows Server 2016
  import_tasks: post_upgrade.yml

