---
# tasks file for win2012_upgrade_2016
- name: Copy and mount Windows Server 2016 ISO file
  block:
    - name: Create '{{ iso_src}}' directory
      win_file:
        path: '{{ iso_src }}'
        state: directory				

    - name: Copy config files from local
      win_copy:
        src: '{{ scripts_location }}/{{ item }}'
        dest: '{{ iso_src }}\'
      with_items:
        - setupcomplete.cmd
        - ConfigureRemotingForAnsible.ps1

    - name: Copy 2K19 ISO file from SDS NIM
      win_copy:
        src: '{{ iso2016 }}'
        dest: '{{ iso_src }}\\en_windows_server_2016.iso'
        remote_src: yes
#      become: yes
#      become_method: runas
#      become_user: Administrator

